### PR TITLE
[New Feature] Support Table datatype in mutations

### PR DESCRIPTION
**Pull request by bobo23**

### CODE REVIEW

**Comment by mcop1** [comment]
Hello @bobo23 
thanks for your contribution. Could you please merge the 1.x branch into your pr branch? This should fix the problems with the tests.

**Comment by mcop1** [comment]
Hello @bobo23 
thanks for your contribution. Could you please merge the 1.x branch into your pr branch? This should fix the problems with the tests.

**Comment by Corepex** [comment]
Here we have the same issue as in the other PR. Please add the resolver to your PR. :)

For more details see; https://github.com/pimcore/data-hub/pull/652#issuecomment-1383863022

**Comment by Corepex** [comment]
@bobo23  friendly reminder ⏰ 🍭

**Comment by Corepex** [comment]
@bobo23 could you please resolve the phpstan issues so that I can recheck that PR as well 😄 👍

**Comment by Corepex** [comment]
@bobo23 friendly reminder ⏰ 🍭

**Comment by bobo23** [comment]
@Corepex sorry for the late response. I hope everything is working now. Please let me know if there are still issues.

**Comment by Corepex** [comment]
@bobo23, thanks - everything works as expected - thanks for your PR 👍 🥇

**Pull request merged**
