### PR TITLE
Support variants in Query

### PR DESCRIPTION
**Pull request by dvesh3**

### CODE REVIEW

**Comment by romainbessugesmeusy** [comment]
Hey ! How should we do if we want to grab objects and not their variants. Or access the variants as a sub objects? I'd ultimately like to do something like that:
Capture d’écran 2020-01-30 à 14 38 43

**Comment by julmot** [comment]
@romainbessugesmeusy We're using something like this:

```gql
colorVariants: children(objectTypes: ["variant"]) {
  // ...
}
```

**Comment by Anne-chaG** [comment]
Hey ! 

I tried to use that type of syntax  

> ```graphql
> colorVariants: children(objectTypes: ["variant"]) {
>   // ...
> }
> ```

and lots of workarounds,  but nothing works.

Maybe i missed something ? (classes definition ? query schema ?)

**Comment by romainbessugesmeusy** [comment]
Hey @julmot do you have a working example? We're a bit stuck with @Anne-chaG here. What version of data-hub are you using?

**Comment by julmot** [comment]
Hey guys,

We've (@CandoImage) created [this PR](https://github.com/pimcore/data-hub/pull/150) to allow fetching children objects with the above syntax. Unfortunately the PR didn't make it to the master yet, so we're using our [own repository](https://github.com/CandoImage/data-hub/tree/parent-children-sibling-objects) including that PR for the meantime.

**Comment by romainbessugesmeusy** [comment]
Can we help to make the PR go live on master? It looked like there were minor changes requested by @weisswurstkanone.

**Comment by weisswurstkanone** [comment]
There are still unresolved conversations + a merge conflict. Can you have a look at that please?

**Comment by julmot** [comment]
Thanks. Yes, we're aware of that and @juckerf will finsish this PR as soon as he'll find the time in our current project, since @AlsonPL is no longer working for us – he took over the work for a couple of days.

**Pull request merged**
