### PR TITLE
Fix Video fullpath and imageThumbnail 

### PR DESCRIPTION
**Pull request by danielerne**
This fixes the broken fullpath param on video assets and adds correct imageThumbnail support for video assets

... on asset {
            id
             image: fullpath(thumbnail: "thumb")
             fullpath
}

Bug produced in #392

### CODE REVIEW

**Comment by danielerne** [comment]
I added the feature for video thumbnails too. So we can decide if we want the preview thumbnail image or the video thumbnail now with an additional format argument:
... on asset {
                        id
                        image: fullpath(thumbnail: "imageThumb", format: "image")
                        mimetype
                        fullpath: fullpath(thumbnail: "videoThumb", format: "mp4")
              }
              
Maybe the format title for image can be discussed. Could be "preview-image" or "preview" too.

**Comment by weisswurstkanone** [comment]
Since this is a bug ... please rebase onto 1.0

**Comment by danielerne** [comment]
Maybe I did it wrong. I'm sorry. Let me know. Otherwise I will fork the 1.0 branch

**Comment by weisswurstkanone** [comment]
Yes, indeed, looks quite odd. Please proceed as how you suggested! Thanks a lot!

**Pull request closed without merging**
