### PR TITLE
[Improvement]: Added replace table option and multi row update

### PR DESCRIPTION
**Pull request by bobo23**

### CODE REVIEW

**Comment by mcop1** [comment]
Hello @bobo23 ,
could you please merge the 1.x branch into your pr again? This should fix the current tests.
Thank you

**Comment by bobo23** [comment]
Hi @mcop1 
done, looks better now.

**Comment by mcop1** [comment]
> Hi @mcop1 done, looks better now.

That was fast, thank you :)

**Comment by lukmzig** [comment]
Thank you for this improvement @bobo23

**Pull request merged**
