### PR TITLE
Replace plugin to bundle in frontend namespace

### PR DESCRIPTION
**Pull request by vmalyk**
1. Changed old namespace from Pimcore 4 (.plugin) to Pimcore 5/6 (.bundle) for consistency
2. Removed extra lines in js files

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
not sure how Pimcore manages SemVer with this Bundle, but this is considered a BC break. CoreShop already implements it's own data-types into data-hub. With this PR, it will stop working

**Comment by dpfaffenbauer** [comment]
I mean, it's not a full 1.0 yet... so BC breaks are allowed, but still....

**Comment by weisswurstkanone** [comment]
With this change the datahub UI vanishes completely

**Comment by weisswurstkanone** [comment]
Probably because of this line

pimcore.bundle.datahub = Class.create(pimcore.bundle.admin, {

**Comment by weisswurstkanone** [comment]
see https://pimcore.com/docs/5.x/Development_Documentation/Extending_Pimcore/Bundle_Developers_Guide/Plugin_Backend_UI.html

**Comment by weisswurstkanone** [comment]
Hi, now configurations cannot be opened.
Did you do any hands-on testing or just search & replace ?

Regardless of that, is there anybody out there with objections against the "BC break"? Or in other words, are there any custom operator/data type implementations already?

**Comment by dpfaffenbauer** [comment]
Yes, CoreShop ;)

**Comment by vmalyk** [comment]
@weisswurstkanone and @dpfaffenbauer, if you think these changes are not finalized, BC or irrelevant - I declined PR. By the way, CoreShop implemented some classes on Early preview module? If it`s true, some some another changes `ll be break  theirs  code ( and they know that(and not only CoreShop)) on non released version (ex 1.0.0).

**Comment by dpfaffenbauer** [comment]
Not sure what you mean....

**Pull request closed without merging**
