### PR TITLE
Add EventListener to dedicated EventListener Class

### PR DESCRIPTION
**Pull request by solverat**
Beside of improving symfony standards, this will prevent exceptions like these (while executing tests for example):

image

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
Hi, two things
- please don't forget the documents
- second and more important: the master configuration is still saved in datahub-configurations.php
Workspace permissions are written to database just for performance reasons.

**Comment by solverat** [comment]
@weisswurstkanone:

1. Alright, I just added them (I didn't really forget them, they just wasn't there before).
2. I don't really know what to do with this fact: Is there anyhing I need to do?

**Comment by solverat** [comment]
@weisswurstkanone ah! you're talking about those elements, right:

image

Shouldn't we use IDs instead of paths in the first place? Could save us some troubles (like the current rename issue for example)

**Comment by solverat** [comment]
Second thought: IDs would be nice but it wouldn't solve the problem. 

I'll add a method which will check the configuration file like you suggested.

**Comment by solverat** [comment]
@weisswurstkanone: Alright, the latest commit:

- checks configuration file for changed values (modified or deleted). If so, adopt the changes
- checks modification date of configuration file (similar to the class definition editor). if there are mismatches, force user to reload config

**Comment by NiklasBr** [comment]
> Shouldn't we use IDs instead of paths in the first place? Could save us some troubles (like the current rename issue for example)

That saves some trouble, absolutely. But it also adds potential problems elsewhere: Running test environments where almost daily builds and reinstallations cause the database id:s of objects to change.

**Comment by solverat** [comment]
@NiklasBr: i know, That‘s why i kept it that way.

**Comment by dpfaffenbauer** [comment]
We had that ID/Path discussion already many times. Since an ID is environment specific, we always have to work with Paths instead. Thats basically the only reason

**Comment by weisswurstkanone** [comment]
As I said I think that manipulating the database directly is not necessary as this is done implicitely by Configuration::save

see https://github.com/pimcore/data-hub/blob/48047edc056d946b80c51de020d0a54146738926/src/Configuration.php#L173

The existing event handler is probably just a leftover.

**Comment by solverat** [comment]
@weisswurstkanone : that's not entirely true. If you're changing or deleting a document/asset/object directly, you also need to update the db workspaces (the `saveWorkspaces` only updates the db if you modify the configuration itself.) You can check that by disabling the event listener.

**Comment by weisswurstkanone** [comment]
Yes that's absolutely true and I am aware of that. I was just saying that we shouldn't fix do things twice since we need the existing db update logic when you save an existing configuration :-)

**Comment by weisswurstkanone** [comment]
thanks a lot!

**Pull request merged**
