### PR TITLE
Sort items in the datahub

### PR DESCRIPTION
**Pull request by jeremygnoonan**
Sorts data hub list:

~~* Folders come first, sorted~~
* Items in folders are sorted
* Things outside of folders are sorted and included second

### CODE REVIEW

**Comment by NiklasBr** [comment]
Please don't sort folders first, it is unintuitive and breaks expectations.

**Comment by jeremygnoonan** [comment]
@NiklasBr I removed the folder first sorting, and also made it case insensitive to behave like the object tree.

**Comment by mcop1** [comment]
Hello @jeremygnoonan,
thank you for the pr, code works fine. 

What do you think about sorting by type too? With different data-hub plugins it would look something like this right now: 
image

Personally I would like it a bit more if we sort by plugin type too. But I guess that would go in the same directions as sorting the folders. Any opinions on that? @NiklasBr ?

**Comment by mcop1** [comment]
To keep things short, I created a follow up ticket to sort configurations in the front end (where sorting should really be imo). Feedback is welcome of course -> https://github.com/pimcore/data-hub/issues/826 

Thanks again for the pr!

**Comment by NiklasBr** [comment]
Just alphabetical natural sorting IMO is great, everything else is known to cause undue cognitive load.

**Comment by jeremygnoonan** [comment]
Thanks guys hope you had a great holiday!

**Pull request merged**
