### PR TITLE
[Task]: Replace Request::get with explicit input sources 

### LINKED ISSUE #679: Replace Request::get with explicit input sources
### Improvement description

see details https://github.com/pimcore/pimcore/issues/14138#issue-1556426476

### PR DESCRIPTION
**Pull request by kingjia90**
Resolves https://github.com/pimcore/data-hub/issues/679
Related https://github.com/pimcore/pimcore/issues/14138

### CODE REVIEW

**Comment by mattamon** [comment]
@kingjia90 What does it need to be finished? Could we already merge it?

**Review by mcop1 — COMMENTED** [review]
Do we also need to update https://github.com/pimcore/data-hub/blob/836c6906b2a8238f51cbee477dd14319b84740b3/doc/10_GraphQL/10_Events.md#L260 & https://github.com/pimcore/data-hub/blob/836c6906b2a8238f51cbee477dd14319b84740b3/doc/10_GraphQL/10_Events.md#L273 ?

**Comment by kingjia90** [comment]
> Do we also need to update
> 
> https://github.com/pimcore/data-hub/blob/836c6906b2a8238f51cbee477dd14319b84740b3/doc/10_GraphQL/10_Events.md#L260
> 
> &
> https://github.com/pimcore/data-hub/blob/836c6906b2a8238f51cbee477dd14319b84740b3/doc/10_GraphQL/10_Events.md#L273
> 
> ?

no needed because it's not marked as internal
https://github.com/symfony/http-foundation/blob/f602d5c17d1fa02f8019ace2687d9d136b7f4a1a/Request.php#L1125-L1138
and itself seems using the right explicit source approach
https://github.com/symfony/http-foundation/blob/f602d5c17d1fa02f8019ace2687d9d136b7f4a1a/Request.php#L1153

**Comment by mcop1** [comment]
Ok, then it looks good to me, thanks :)

**Pull request merged**
