### PR TITLE
Bump pimcore version to ^10.2

### PR DESCRIPTION
**Pull request by blankse**
See https://github.com/pimcore/pimcore/discussions/10811

### CODE REVIEW

**Comment by dvesh3** [comment]
please rebase on 1.1 branch. thanks!

**Comment by blankse** [comment]
@dvesh3 Changed the target branch

**Comment by dvesh3** [comment]
@blankse thanks!

**Comment by ramundomario** [comment]
@dvesh3 Just installed data-hub on a project currently running Pimcore 6.9 (which we are migrating to Pimcore X).
The version installed by the composer is v1.1.0 and from what I've read it seems to be wrong.
What is the latest version running on Pimcore 6? I guess 1.0.x, right? Thanks!

**Comment by dvesh3** [comment]
@ramundomario Hi! yes, please use version 1.0.11 on Pimcore 6.9.

**Pull request merged**
