### PR TITLE
Fix DocumentTreeType 

### PR DESCRIPTION
**Pull request by dlhck**
duplicate type `_document_folder`

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
HI @davidhoeck , I see the issue :-) Does it cause a problem and how to reproduce. If so then this is rather something for the bugfix release. Thanks for your feedback!

**Comment by dlhck** [comment]
@weisswurstkanone when using `*Listing` queries the error is happening, because the allowed types of a union type must be unique, which is not the case. so I think it is rather important to fix that

**Comment by dlhck** [comment]
@weisswurstkanone any update on that?

**Comment by weisswurstkanone** [comment]
Hi @davidhoeck , thanks for your feedback. Since this is a bug could you please rebase it to 1.0 ? Thanks a lot!

**Comment by weisswurstkanone** [comment]
Hi @davidhoeck , fixed it directly via https://github.com/pimcore/data-hub/commit/f9c20decd07b69ebab42dd84232d44e36667ea51

Thanks for your input!

**Pull request closed without merging**
