### PR TITLE
[Documents] Allow fetching translation links

### LINKED ISSUE #528: [Documents] Support for fetching linked translations
### Improvement description

Add support for fetching linked translations from document:
image

### PR DESCRIPTION
**Pull request by dvesh3**
Resolves #528

### CODE REVIEW

**Comment by fashxp** [comment]
@dvesh3 would is also be possible, that we can deliver content of the linked document directly in the request? .. not just ID and language?

**Comment by dvesh3** [comment]
> @dvesh3 would is also be possible, that we can deliver content of the linked document directly in the request? .. not just ID and language?

Added `target` field along with `id` & `language`.

**Review by mcop1 — COMMENTED** [review]
At the moment it is not possible to query folders for translation, e.g.
image

**Comment by dvesh3** [comment]
> At the moment it is not possible to query folders for translation, e.g. image

Added support for document folders.

**Comment by dvesh3** [comment]
> At the moment it is not possible to query folders for translation, e.g. image

Added support for document folders.

**Review by mcop1 — APPROVED** [review]

**Pull request merged**
