### PR TITLE
Asset tags implementation (fixes #345)

### LINKED ISSUE #345: implement asset tags
It would be great to have asset tags to be visible in response of GraphQL query. For example, in response to this query:

```graphql
{
  getAssetListing(ids:"4708") {
    totalCount
    edges {
      node {
        __typename
        ... on asset {
          filename
          type
          tags {
            id
            path
            name
          }
          metadata {
            name
          }
          properties {
            ... on property_text {
              name
            }
          }
        }
        ... on asset_folder {
          fullpath
          filename
        }
      }
    }
  }
}
```

to have something similar to this:
```json
{
  "data": {
    "getAssetListing": {
      "totalCount": 1,
      "edges": [
        {
          "node": {
            "__typename": "asset",
            "filename": "KA-2105_0000_unknown_1561.jpg",
            "type": "image",
            "tags": [
              {
                "id": "8",
                "path": "/Brand/KOVEA",
                "name": "KOVEA"
              }
            ],
            "metadata": null,
            "properties": []
          }
        }
      ]
    }
  }
}
```

### PR DESCRIPTION
**Pull request by ab-kily**
I'm providing pull request that fixes #345 issue.

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
@ab-kily looks good. but would be a good opportunity to implement this for documents and objects as well in one go. would be warmly appreciated!

**Comment by weisswurstkanone** [comment]
and please don't forget to sign the CLA ? Thanks a lot 👍

**Comment by ab-kily** [comment]
> and please don't forget to sign the CLA ? Thanks a lot

I've signed it already, but my commit is from "root" user... Should I provide new PR with correct credentials?

**Comment by weisswurstkanone** [comment]
give it a try please 👍

**Pull request closed without merging**
