### PR TITLE
[New Feature] Support ImageGallery datatype in mutations

### PR DESCRIPTION
**Pull request by bobo23**

### CODE REVIEW

**Comment by mcop1** [comment]
Hello @bobo23 
thanks for your contribution. Could you please merge the 1.x branch into your pr branch? This should fix the problems with the tests.

**Comment by Corepex** [comment]
@bobo23 thanks for your PR. I tested the mutation part and it works smoothly so far. 
Nevertheless, it seems that you haven't provided the "resolver" part ...

You can have a look at this PR: https://github.com/pimcore/data-hub/pull/634
Here you can find the resolver part of the PR: https://github.com/ultramegatom/data-hub/blob/571164166ca0d1d6249a5bc2f4fb81a722638fc3/src/GraphQL/Resolver/Link.php

Please add the resolver to your PR. 
I'm really looking forward to review it 🪂 🎉

**Comment by Corepex** [comment]
@bobo23  friendly reminder ⏰ 🍭

**Comment by Corepex** [comment]
@bobo23 looked at this PR again. It looks like I forgot to add the according asset workspace... 
After adding this works perfectly - many sorry for the inconvenience. 🍭

**Pull request merged**
