### PR TITLE
Use DataObject instead of AbstractObject, AbstractObject can't be instantiated anymore in pimcore x

### PR DESCRIPTION
**Pull request by Iblis**

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
Thx! Could you please rebase it on 1.0?

**Comment by Iblis** [comment]
Is rebasing enough or do I need to change the PR's target from 1.x to 1.0, too?

**Comment by weisswurstkanone** [comment]
Hello @Iblis the change would be necessary here 

image

**Comment by Iblis** [comment]
Sorry, I might have messed this up now ^^. Should I just create a new PR, basing it on branch 1.0?

**Comment by weisswurstkanone** [comment]
@Iblis  yes please 👍

**Comment by Iblis** [comment]
https://github.com/pimcore/data-hub/pull/407

**Pull request closed without merging**
