### PR TITLE
Fix asset mutation method

### PR DESCRIPTION
**Pull request by dzhdan**
Fix asset mutation method

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
Hello @dzhdan , could you please sign the CLA? Thanks a lot!

**Comment by weisswurstkanone** [comment]
@dzhdan CLA agreement is still pending

**Comment by weisswurstkanone** [comment]
@dzhdan ping

In addition, please provide a mutation sample which will fail.

**Comment by dzhdan** [comment]
@weisswurstkanone 
I've already signed
You have signed the CLA for pimcore/data-hub
Version: 2016-02-05
But still can see that message, that I am not signed

**Comment by weisswurstkanone** [comment]
thanks a lot!

**Pull request closed without merging**
