### PR TITLE
[Admin] Explorer - Fix open in tab

### LINKED ISSUE #217: Error: Parameter "clientname" for route "admin_pimcoredatahub_config"
We've just pulled the most recent DataHub changes and got the following error when clicking on the "Open in Tab" button in the schema editor:

Maybe related to:
https://github.com/CandoImage/data-hub/commit/61bc92d6195df960a2daafd15d4e4fab0a7be84d

### PR DESCRIPTION
**Pull request by dvesh3**
Resolves #217

### CODE REVIEW

**Comment by weisswurstkanone** [comment]
what is the difference to https://github.com/CandoImage/data-hub/commit/61bc92d6195df960a2daafd15d4e4fab0a7be84d ?

**Comment by weisswurstkanone** [comment]
@julmot , could you please check if this change works for you?

**Comment by dvesh3** [comment]
> what is the difference to [CandoImage@61bc92d](https://github.com/CandoImage/data-hub/commit/61bc92d6195df960a2daafd15d4e4fab0a7be84d) ?

changes here https://github.com/pimcore/data-hub/pull/218/files#diff-18cfbbef8328be680bd0be89cebabeb0

**Comment by weisswurstkanone** [comment]
thx @dvesh3

**Pull request merged**
